#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHPANEL_FOCAL) += focal_common.o
obj-$(CONFIG_TOUCHPANEL_FOCAL_FT8006) += FT8006/
obj-$(CONFIG_TOUCHPANEL_FOCAL_FT3518) += ft3518/
obj-$(CONFIG_TOUCHPANEL_FOCAL_FT8006S_AA) += ft8006s_aa/
obj-$(CONFIG_TOUCHPANEL_FOCAL_FT3681) += ft3681/

#endif
