subdir-ccflags-y += -I$(srctree)/$(src)

obj-y      += op_wlchg/

obj-y      += charger_ic/
obj-y      += gauge_ic/
obj-y      += vooc_ic/
obj-y      += adapter_ic/
obj-y	   += chargepump_ic/
obj-y	   += oplus_pps_ops_manager.o

obj-y      += voocphy/

obj-y	+= oplus_charger.o
obj-y	+= oplus_battery_log.o
obj-y	+= oplus_gauge.o
obj-y	+= oplus_vooc.o
obj-y	+= oplus_adapter.o
obj-y 	+= oplus_chg_track.o
obj-y 	+= oplus_quirks.o

obj-y	+= oplus_wlchg_policy.o

obj-y	+= oplus_short.o
obj-y   += oplus_debug_info.o
obj-y   += oplus_chg_ops_manager.o
obj-y	+= oplus_pps.o
obj-y   += oplus_configfs.o
obj-y   += charger_ic/oplus_switching.o
obj-y   += chargepump_ic/
obj-y	+= oplus_pps_ops_manager.o
obj-y 	+= oplus_quirks.o
obj-y   += oplus_region_check.o

obj-y += oplus_chg_voter.o
obj-y += oplus_chg_core.o
obj-y += oplus_chg_comm.o

obj-y += ufcs/
obj-y += oplus_ufcs.o
obj-y += oplus_chg_exception.o
obj-y += bob_ic/oplus_tps6128xd.o
