#
# Makefile for the touchscreen drivers.
#

ccflags-y += -Wall

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHPANEL_ILITEK_ILITEK7807S)  += ili7807s_qcom.o \
                                                ili7807s_ic.o \
                                                ili7807s_mp.o \
                                                ili7807s_fw.o \
                                                ili7807s_node.o
#endif
