#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHPANEL_ILITEK_ILITEK9881H_V2)  += ilitek_drivers_ili9881h.o userspace.o firmware.o mp_test.o protocol.o
#endif