# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2020-2021 Oplus. All rights reserved.

oplus_bsp_midas-objs := \
	binder_stats_dev.o \
	midas_dev.o \
	midas_ioctl.o \
	midas_cpu.o \
	midas_mem.o \
	midas_module.o

obj-$(CONFIG_OPLUS_FEATURE_MIDAS_V2) += oplus_bsp_midas.o
