	obj-y   += oplus_sc8571_master.o
	obj-y   += oplus_sc8571_slave.o
	obj-y   += oplus_bq25980_master.o
	obj-y   += oplus_bq25980_slave.o
	obj-y   += oplus_nu2205_master.o
	obj-y   += oplus_nu2205_slave.o
	obj-y   += oplus_pps_cp.o