# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.
obj-$(CONFIG_OPLUS_FEATURE_QCOM_MINIDUMP_ENHANCE) += qcom_minidump_enhance.o
obj-$(CONFIG_OPLUS_FEATURE_QCOM_MINIDUMP_ENHANCE) += get_regs.o