#
# Makefile for the touchscreen drivers.
#

obj-$(CONFIG_TOUCHPANEL_SAMSUNG) += sec_common.o
obj-$(CONFIG_TOUCHPANEL_SAMSUNG_S6SY771) += S6SY771/
obj-$(CONFIG_TOUCHPANEL_SAMSUNG_S6SY791) += S6SY791/
