obj-$(CONFIG_OPLUS_FINGERPRINT) += oplus_fp_common/

### Optical fingerprint sensor
obj-$(CONFIG_OPLUS_FINGERPRINT_JIIOV_OPTICAL)	+= anc_driver/
obj-$(CONFIG_OPLUS_FINGERPRINT_GOODIX_OPTICAL)	+= goodix_optical_fp/
