#for AWINIC AW8697 Haptic
#ifdef OPLUS_FEATURE_CHG_BASIC
ccflags-y += -DCONFIG_OPLUS_HAPTIC_OOS
#endif
obj-$(CONFIG_AW8697_HAPTIC) += aw8697.o

obj-$(CONFIG_AW8697_HAPTIC) += haptic.o
haptic-objs := aw8692x.o haptic_hv.o
