# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.
ifneq ($(CONFIG_OPLUS_FEATURE_SAUPWK),n)
ccflags-y += -I$(srctree)/drivers/ -I$(srctree)/drivers/input/
endif
obj-$(CONFIG_OPLUS_FEATURE_SAUPWK) += oplus_saupwk.o
