#ifdef OPLUS_FEATURE_TASK_CPUSTATS
obj-$(CONFIG_OPLUS_CTP) += task_cpustats.o
obj-$(CONFIG_OPLUS_SCHED) += task_sched_info.o
obj-$(CONFIG_UTILS_MONITOR) += task_load.o
#endif /* OPLUS_FEATURE_TASK_CPUSTATS */
