#ifdef OPLUS_FEATURE_HEALTHINFO
obj-$(CONFIG_OPLUS_HEALTHINFO)  +=  cpuload.o
obj-$(CONFIG_OPLUS_JANK_INFO)  +=  jank_monitor.o
#endif /* OPLUS_FEATURE_HEALTHINFO */
obj-$(CONFIG_FG_TASK_UID)  +=  fg_uid/
