ifeq ($(CONFIG_OPLUS_FINGERPRINT_MTK),y)
jiiov_cap_mtk-y += jiiov_platform_mtk.o jiiov_netlink.o
obj-y += jiiov_cap_mtk.o
else
jiiov_cap_qcom-y += jiiov_platform.o jiiov_netlink.o
obj-y += jiiov_cap_qcom.o
endif
