# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.
obj-$(CONFIG_OPLUS_FEATURE_PHOENIX) += op_bootprof.o
obj-$(CONFIG_OPLUS_FEATURE_PHOENIX) += phoenix_base.o
obj-$(CONFIG_OPLUS_FEATURE_PHOENIX) += phoenix_dump.o
obj-$(CONFIG_OPLUS_FEATURE_PHOENIX) += phoenix_watchdog.o
obj-$(CONFIG_OPLUS_FEATURE_KMSG_WB) += oplus_kmsg_wb.o
obj-$(CONFIG_OPLUS_FEATURE_PHOENIX_REBOOT_SPEED) += phoenix_reboot_speed.o
