# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2020-2021 Oplus. All rights reserved.

obj-$(CONFIG_OPLUS_FEATURE_MIDAS) += v1/
obj-$(CONFIG_OPLUS_FEATURE_MIDAS_GKI) += v1_gki/
obj-$(CONFIG_OPLUS_FEATURE_MIDAS_V2) += v2/
