#
# Makefile for the touchscreen drivers.
#

obj-$(CONFIG_TOUCHPANEL_OPLUS) += util_interface/
obj-$(CONFIG_TOUCHPANEL_OPLUS) += touchpanel_common_driver.o
obj-$(CONFIG_TOUCHPANEL_SAMSUNG) += Samsung/
obj-$(CONFIG_TOUCHPANEL_SYNAPTICS) += Synaptics/
