# SPDX-License-Identifier: GPL-2.0-only
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_v2
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_v2/common
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_v2/sensor/io
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_v2/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
