#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHPANEL_HIMAX) += himax_common.o
obj-$(CONFIG_TOUCHPANEL_HIMAX_HX83112B) += hx83112b/
obj-$(CONFIG_TOUCHPANEL_HIMAX_HX83112A_NOFLASH) += hx83112a_noflash/
obj-$(CONFIG_TOUCHPANEL_HIMAX_HX83112B_NOFLASH) += hx83112b_noflash/
obj-$(CONFIG_TOUCHPANEL_HIMAX_HX83102D_NOFLASH) += hx83102d_noflash/
obj-$(CONFIG_TOUCHPANEL_HIMAX_HX83112F_NOFLASH) += hx83112f_noflash/
#endif
