ifeq ($(CONFIG_OPLUS_SM8250_CHARGER),y)
	obj-y   += oplus_charge_pump.o
	obj-y	+= oplus_da9313.o
	obj-y	+= oplus_battery_msm8250.o
	obj-y	+= oplus_mp2650.o
	obj-y   += oplus_usbtemp.o
endif

	obj-y   += oplus_short_ic.o
