#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHPANEL_FOCAL_FT3518) += focal_drivers_ft3518.o
obj-$(CONFIG_TOUCHPANEL_FOCAL_FT3518) += focal_test_ft3518.o
