#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHPANEL_ILITEK_ILITEK9881H_V3)  += ilitek_plat_qcom.o \
                                                   ilitek_ic.o \
                                                   ilitek_mp.o \
                                                   ilitek_fw.o \
                                                   ilitek_node.o
#endif
