obj-$(CONFIG_OPLUS_COMMON_SOFT)  +=  device_info/

#ifdef VENDOR_EDIT
obj-$(CONFIG_OPLUS_FEATURE_MIDAS)    += midas/
#endif /* VENDOR_EDIT */

#ifdef OPLUS_FEATURE_THERMAL_HORAE
obj-$(CONFIG_HORAE_THERMAL_SHELL) += thermal/
#endif /* OPLUS_FEATURE_THERMAL_HORAE */

#ifdef OPLUS_FEATURE_GPIO_NC
obj-$(CONFIG_OPLUS_GPIO_NC) +=  oplus_gpio/
#endif

