#ifdef OPLUS_FEATURE_TP_BASIC
obj-$(CONFIG_OPLUS_DEVICE_IFNO) += device_info/
#endif /* OPLUS_FEATURE_TP_BASIC */
#ifdef OPLUS_FEATURE_ESIM
obj-y += misc/
#endif /* OPLUS_FEATURE_ESIM */
#ifdef OPLUS_FEATURE_THERMAL_HORAE
obj-$(CONFIG_HORAE_THERMAL_SHELL) += thermal/
#endif /* OPLUS_FEATURE_THERMAL_HORAE */
#ifdef OPLUS_FEATURE_SENSOR_SMEM
obj-y += sensor/
#endif
#ifdef VENDOR_EDIT
obj-$(CONFIG_OPLUS_SYSTEM_KERNEL) += system/
#endif /* VENDOR_EDIT */
