#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHPANEL_ILITEK_ILITEK9881H) += ilitek9881h/
obj-$(CONFIG_TOUCHPANEL_ILITEK_ILITEK9881H_V2) += ilitek9881h_v2/
obj-$(CONFIG_TOUCHPANEL_ILITEK_ILITEK9881H_V3) += ilitek9881h_v3/
obj-$(CONFIG_TOUCHPANEL_ILITEK_ILITEK9882N) += ilitek9882n/
obj-$(CONFIG_TOUCHPANEL_ILITEK_ILITEK7807S) += ilitek7807s/
#endif
