# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.
obj-$(CONFIG_OPLUS_FEATURE_MISC) += oplus_misc.o
obj-$(CONFIG_PARAM_READ_WRITE) += param_read_write.o
obj-$(CONFIG_BOOTLOADER_LOG)	+= bootloader_log.o
#obj-$(CONFIG_WB_KERNEL_LOG) += wb_kernel_log.o
