#
# Makefile for the touchscreen drivers.
#

ccflags-y += -Wall

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHPANEL_ILITEK_ILITEK9882N)  += ili9882n_qcom.o \
                                                ili9882n_ic.o \
                                                ili9882n_mp.o \
                                                ili9882n_fw.o \
                                                ili9882n_node.o
#endif
