# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.
obj-$(CONFIG_OPLUS_FEATURE_PMIC_MONITOR)	 += pmic_monitor.o
pmic_monitor-objs := oplus_pmic_info_smem.o main.o


