# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.

#ifdef OPLUS_FEATURE_MIDAS
oplus_midas-objs := midas_proc.o dispcap_dev.o vpu_pw_off_latency_proc.o
obj-$(CONFIG_OPLUS_FEATURE_MIDAS) += oplus_midas.o
#endif /* OPLUS_FEATURE_MIDAS */

