# SPDX-License-Identifier: GPL-2.0-only
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_v2
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_v2/msm_vb2
obj-$(CONFIG_MSMB_CAMERA) += msm_vb2.o
