# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.

oplus_bsp_midas-objs := \
	binder_stats_dev.o \
	midas_dev.o \
	midas_ioctl.o \
	midas_module.o

obj-$(CONFIG_OPLUS_FEATURE_MIDAS_GKI) += oplus_bsp_midas.o
