#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHPANEL_FOCAL_FT8006S_AA) += focal_drivers_ft8006s_aa.o
obj-$(CONFIG_TOUCHPANEL_FOCAL_FT8006S_AA) += focal_test_ft8006s_aa.o
