# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.
obj-$(CONFIG_OPLUS_FEATURE_SAUPWK) += saupwk.o
obj-$(CONFIG_OPLUS_FEATURE_ANDROIDBOOT) += androidboot.o
obj-$(CONFIG_OPLUS_FEATURE_FTMMODE) 	+= oplus_ftm_mode.o
obj-$(CONFIG_OPLUS_FEATURE_CHARGERPRESENT) 	+= oplus_charger_present.o
obj-$(CONFIG_OPLUS_FEATURE_BUILDVARIANT) 	+= buildvariant.o
obj-$(CONFIG_OPLUS_FEATURE_SIMCARDNUM) 	+= simcardnum.o
obj-$(CONFIG_OPLUS_FEATURE_CDT)	+= cdt_integrity.o
obj-$(CONFIG_OPLUS_FEATURE_SHUTDOWN_SPEED)	+= shutdown_speed.o
