#
# Makefile for the Synaptics TCM touchscreen driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHPANEL_SYNAPTICS_TD4320) += synaptics_tcm_spi.o
obj-$(CONFIG_TOUCHPANEL_SYNAPTICS_TD4320) += synaptics_tcm_core.o
obj-$(CONFIG_TOUCHPANEL_SYNAPTICS_TD4320) += synaptics_tcm_touch.o
obj-$(CONFIG_TOUCHPANEL_SYNAPTICS_TD4320) += synaptics_tcm_device.o
obj-$(CONFIG_TOUCHPANEL_SYNAPTICS_TD4320) += synaptics_tcm_testing.o
obj-$(CONFIG_TOUCHPANEL_SYNAPTICS_TD4320) += synaptics_tcm_reflash.o
obj-$(CONFIG_TOUCHPANEL_SYNAPTICS_TD4320) += synaptics_tcm_recovery.o
obj-$(CONFIG_TOUCHPANEL_SYNAPTICS_TD4320) += synaptics_tcm_zeroflash.o
obj-$(CONFIG_TOUCHPANEL_SYNAPTICS_TD4320) += synaptics_tcm_diagnostics.o
