# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.
obj-$(CONFIG_OPLUS_FEATURE_THEIA) += black_screen_check.o
obj-$(CONFIG_OPLUS_FEATURE_THEIA) += bright_screen_check.o
obj-$(CONFIG_OPLUS_FEATURE_THEIA) += theia_kevent_kernel.o
obj-$(CONFIG_OPLUS_FEATURE_THEIA) += powerkey_monitor.o
